Add issuer to the loaderContext
webpack/core pull request #26
Opened 2016-09-24 00:44 UTC by carlosmarte

I would like to add the issuer to the loaderContext object.

This property will be use for debugging and logging during development. 
```javascript
module.exports = function(source) {
 console.log(this.issuer);
}
```

2016-09-30 14:25 UTC, TheLarkInn requested changes
This repo is obsolete and not used anymore. Did you mean for this to be in webpack/loader-runner or webpack/enhanced-resolve or something separate?

2016-10-13 05:23 UTC, carlosmarte commented
@TheLarkInn, i was planning on using it as a loader. I want to create a loader that will append html comment to angular templates
*something like*:
```js
module.exports = function(source) {
 console.log(this.issuer);
  return `
    <!--
        - view: ${this.resourcePath}
        - controller: ${this. issuer}
     -->
    ${source}
  `;
}
```

This would be use for development. On large legacy apps it hard to trace down all the views and which controller was called. 

Thank you in advance for your help.

2016-10-15 17:47 UTC, carlosmarte commented
@TheLarkInn, I'm supporting a legacy project that still uses this repo. I would prefer to update the build script and webpack version, but that's not an option. for now having this in webpack-core would help me with debugging.

If possible i would like to have this feature in webpack/loader-runner. but I'll open a separate PR for that to be review. 

Thanks in advance

2016-12-05 17:03 UTC, sokra commented
This feature is in webpack 2

2016-12-05 17:03 UTC, closed without merging

2017-09-17 03:15 UTC, carlosmarte commented
Thanks @sokra is there a documentation page on this?

2017-09-19 18:25 UTC, TheLarkInn commented
webpack.js.org/configuration/module